INSERT INTO food_type VALUES (1, 'Verduras');
INSERT INTO food_type VALUES (2, 'Frutas');
INSERT INTO food_type VALUES (3, 'Cereales y Tubérculos');
INSERT INTO food_type VALUES (4, 'Leguminosas');
INSERT INTO food_type VALUES (5, 'Alimentos de Origen Natural');
INSERT INTO food_type VALUES (6, 'Leche');
INSERT INTO food_type VALUES (7, 'Aceites y Grasas');
INSERT INTO food_type VALUES (8, 'Azúcares');
INSERT INTO food_type VALUES (9, 'Aceites y Grasas B');
INSERT INTO food_unit VALUES (1, 'Pieza', 'pz');
INSERT INTO food_unit VALUES (2, 'Taza', 'tza');
INSERT INTO food_unit VALUES (3, 'Cucharada', 'cuch');
INSERT INTO food_unit VALUES (4, 'Cucharadita', 'cuchta');
INSERT INTO food_unit VALUES (5, 'Frasco', 'fsco');
INSERT INTO food_unit VALUES (6, 'Sobre', 'sbr');
INSERT INTO food_unit VALUES (7, 'Rebanada', 'rbda');
INSERT INTO food_unit VALUES (8, 'Paquete', 'pqt');
INSERT INTO food_unit VALUES (9, 'Gramo', 'gr');
INSERT INTO food_unit VALUES (10, 'Mililitros', 'ml');
INSERT INTO daily_menu VALUES (1, 'Menú por defecto');
INSERT INTO daily_menu_entry VALUES (1, 1, 5, 1);
INSERT INTO daily_menu_entry VALUES (2, 1, 4, 2);
INSERT INTO daily_menu_entry VALUES (3, 1, 8, 3);
INSERT INTO daily_menu_entry VALUES (4, 1, 1, 4);
INSERT INTO daily_menu_entry VALUES (5, 1, 5, 4);
INSERT INTO daily_menu_entry VALUES (6, 1, 2, 6);
INSERT INTO daily_menu_entry VALUES (7, 1, 6, 7);
INSERT INTO daily_menu_entry VALUES (8, 1, 0, 8);
INSERT INTO daily_menu_entry VALUES (9, 1, 0, 9);
